version: "3.9"

services:
  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d
      - ./nginx/snippets/:/etc/nginx/snippets
      - ./keys/dhparam.pem:/etc/ssl/certs/dhparam.pem:ro
      - ./keys/server.crt:/etc/ssl/certs/server.crt:ro
      - ./keys/server.key:/etc/ssl/private/server.key:ro
